apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 192.168.88.111
clientConnection:
  kubeconfig: /etc/kubernetes/kube-proxy.kubeconfig
clusterCIDR: 10.20.0.0/16
healthzBindAddress: 192.168.88.111:10256
kind: KubeProxyConfiguration
metricsBindAddress: 192.168.88.111:10249
mode: "iptables"
